# vim:ft=kitty

## name: rtheme
## license: MIT
## author: Rodolfo Barcelli Jo
## upstream: https://github.com/rodolfobar/rtheme


background #110f15
foreground #eeebff
selection_background #342d42
selection_foreground #eeebff
url_color #36ffc3
cursor #eeebff
cursor_text_color #110f15

# Tabs
active_tab_background #6daeff
active_tab_foreground #110f15
inactive_tab_background #342d42
inactive_tab_foreground #706897
#tab_bar_background #110f15

# Windows
active_border_color #6daeff
inactive_border_color #342d42


# normal
color0 #241e2e
color1 #ff4f7f
color2 #a6ff65
color3 #ffa770
color4 #6daeff
color5 #b483ff
color6 #36ffc3
color7 #706897

# bright
color8 #342d42
color9 #ff79a0
color10 #b9ff91
color11 #ffd986
color12 #76ddff
color13 #fb97ff
color14 #6fffe7
color15 #a7a5cb

# extended colors
color16 #ffa770
color17 #ff4f7f
