# vim:ft=kitty

## name: rtheme
## license: MIT
## author: Rodolfo Barcelli Jo
## upstream: https://github.com/rodolfobar/rtheme


background #110f15 
foreground #e8e7ff
selection_background #272133 
selection_foreground #c0caf5
url_color #4cffe1
cursor #e8e7ff
cursor_text_color #15131a

# Tabs
active_tab_background #43d1ff
active_tab_foreground #110f15
inactive_tab_background #382f4a
inactive_tab_foreground #645d87
#tab_bar_background #110f15

# Windows
active_border_color #43d1ff
inactive_border_color #382f4a


# normal
color0 #2d2241
color1 #ff5d8a
color2 #a6ff65
color3 #ffa770
color4 #43d1ff
color5 #a970ff
color6 #00ffb2
color7 #645d87

# bright
color8 #382f4a
color9 #ff8aac
color10 #b9ff91
color11 #ffd986
color12 #86e8ff
color13 #fb97ff
color14 #4cffe1
color15 #9e9cc0

# extended colors
color16 #ffa770
color17 #ff5d8a
