" Name:         RTheme
" Description:  A minimal dark theme
" Author:       Rodolfo Barcelli Jo
" URL:          https://github.com/rodolfobar/rtheme
" License:      MIT
" Last Change:  2026 May 28

" Generated by Colortemplate v3.0.0-rc2

set background=dark

hi clear
let g:colors_name = 'rtheme'

let s:t_Co = has('gui_running') ? 16777216 : str2nr(&t_Co)
let s:tgc = has('termguicolors') && &termguicolors

let g:terminal_ansi_colors = ['#241e2e', '#ff4f7f', '#a6ff65', '#ffa770', '#6daeff', '#b483ff', '#36ffc3', '#706897', '#342d42', '#ff79a0', '#b9ff91', '#ffd986', '#76ddff', '#fb97ff', '#6fffe7', '#a7a5cb']

let s:transp_bg = get(g:, 'rtheme_transp_bg', 0)

hi! link CursorColumn Visual
hi! link CursorLine Visual
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link FloatTitle Title
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link MsgSeparator WinSeparator
hi! link TermCursorNC Cursor
hi! link WinSeparator VertSplit

hi Normal guifg=#eeebff guibg=#110f15 guisp=NONE gui=NONE ctermfg=189 ctermbg=233 cterm=NONE term=NONE
hi ColorColumn guifg=NONE guibg=#241e2e guisp=NONE gui=NONE ctermfg=NONE ctermbg=234 cterm=NONE term=NONE
hi Comment guifg=#706897 guibg=NONE guisp=NONE gui=NONE ctermfg=60 ctermbg=NONE cterm=NONE term=NONE
hi Conceal guifg=#706897 guibg=NONE guisp=NONE gui=NONE ctermfg=60 ctermbg=NONE cterm=NONE term=NONE
hi Constant guifg=#ffa770 guibg=NONE guisp=NONE gui=NONE ctermfg=216 ctermbg=NONE cterm=NONE term=NONE
hi CurSearch guifg=#241e2e guibg=#6fffe7 guisp=NONE gui=bold ctermfg=234 ctermbg=86 cterm=bold term=bold
hi CursorLineNr guifg=#ffa770 guibg=NONE guisp=NONE gui=NONE ctermfg=216 ctermbg=NONE cterm=NONE term=NONE
hi Delimiter guifg=#76ddff guibg=NONE guisp=NONE gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE term=NONE
hi DiffAdd guifg=#b9ff91 guibg=#241e2e guisp=NONE gui=NONE ctermfg=156 ctermbg=234 cterm=NONE term=NONE
hi DiffChange guifg=#76ddff guibg=#241e2e guisp=NONE gui=NONE ctermfg=81 ctermbg=234 cterm=NONE term=NONE
hi DiffDelete guifg=#ff79a0 guibg=#241e2e guisp=NONE gui=NONE ctermfg=211 ctermbg=234 cterm=NONE term=NONE
hi DiffText guifg=#ffa770 guibg=#342d42 guisp=NONE gui=bold ctermfg=216 ctermbg=236 cterm=bold term=bold
hi Directory guifg=#6daeff guibg=NONE guisp=NONE gui=NONE ctermfg=75 ctermbg=NONE cterm=NONE term=NONE
hi EndOfBuffer guifg=#241e2e guibg=#110f15 guisp=NONE gui=NONE ctermfg=234 ctermbg=233 cterm=NONE term=NONE
hi ErrorMsg guifg=#ff4f7f guibg=NONE guisp=NONE gui=bold ctermfg=204 ctermbg=NONE cterm=bold term=bold
hi FloatBorder guifg=#342d42 guibg=#241e2e guisp=NONE gui=NONE ctermfg=236 ctermbg=234 cterm=NONE term=NONE
hi FoldColumn guifg=#706897 guibg=#110f15 guisp=NONE gui=NONE ctermfg=60 ctermbg=233 cterm=NONE term=NONE
hi Folded guifg=#706897 guibg=#110f15 guisp=NONE gui=NONE ctermfg=60 ctermbg=233 cterm=NONE term=NONE
hi Function guifg=#76ddff guibg=NONE guisp=NONE gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE term=NONE
hi Identifier guifg=fg guibg=NONE guisp=NONE gui=NONE ctermfg=fg ctermbg=NONE cterm=NONE term=NONE
hi IncSearch guifg=#241e2e guibg=#76ddff guisp=NONE gui=bold ctermfg=234 ctermbg=81 cterm=bold term=bold
hi LineNr guifg=#706897 guibg=NONE guisp=NONE gui=NONE ctermfg=60 ctermbg=NONE cterm=NONE term=NONE
hi MatchParen guifg=#ffa770 guibg=#342d42 guisp=NONE gui=bold ctermfg=216 ctermbg=236 cterm=bold term=bold
hi ModeMsg guifg=#76ddff guibg=NONE guisp=NONE gui=bold ctermfg=81 ctermbg=NONE cterm=bold term=bold
hi MoreMsg guifg=#b9ff91 guibg=NONE guisp=NONE gui=bold ctermfg=156 ctermbg=NONE cterm=bold term=bold
hi MsgArea guifg=#eeebff guibg=#110f15 guisp=NONE gui=NONE ctermfg=189 ctermbg=233 cterm=NONE term=NONE
hi NonText guifg=#342d42 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE term=NONE
hi NormalFloat guifg=#eeebff guibg=#241e2e guisp=NONE gui=NONE ctermfg=189 ctermbg=234 cterm=NONE term=NONE
hi NormalNC guifg=#eeebff guibg=#110f15 guisp=NONE gui=NONE ctermfg=189 ctermbg=233 cterm=NONE term=NONE
hi Operator guifg=#76ddff guibg=NONE guisp=NONE gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE term=NONE
hi Pmenu guifg=#eeebff guibg=#241e2e guisp=NONE gui=NONE ctermfg=189 ctermbg=234 cterm=NONE term=NONE
hi PmenuSbar guifg=NONE guibg=#342d42 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE term=NONE
hi PmenuSel guifg=#241e2e guibg=#76ddff guisp=NONE gui=bold ctermfg=234 ctermbg=81 cterm=bold term=bold
hi PmenuThumb guifg=NONE guibg=#706897 guisp=NONE gui=NONE ctermfg=NONE ctermbg=60 cterm=NONE term=NONE
hi PreProc guifg=#fb97ff guibg=NONE guisp=NONE gui=NONE ctermfg=213 ctermbg=NONE cterm=NONE term=NONE
hi Question guifg=#36ffc3 guibg=NONE guisp=NONE gui=bold ctermfg=49 ctermbg=NONE cterm=bold term=bold
hi QuickFixLine guifg=NONE guibg=#241e2e guisp=NONE gui=bold ctermfg=NONE ctermbg=234 cterm=bold term=bold
hi Search guifg=#241e2e guibg=#ffd986 guisp=NONE gui=NONE ctermfg=234 ctermbg=222 cterm=NONE term=NONE
hi SignColumn guifg=#eeebff guibg=#110f15 guisp=NONE gui=NONE ctermfg=189 ctermbg=233 cterm=NONE term=NONE
hi Special guifg=fg guibg=NONE guisp=NONE gui=NONE ctermfg=fg ctermbg=NONE cterm=NONE term=NONE
hi SpecialKey guifg=#342d42 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE term=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#ff4f7f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl term=undercurl ctermul=204
hi SpellCap guifg=NONE guibg=NONE guisp=#76ddff gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl term=undercurl ctermul=81
hi SpellLocal guifg=NONE guibg=NONE guisp=#6fffe7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl term=undercurl ctermul=86
hi SpellRare guifg=NONE guibg=NONE guisp=#b483ff gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl term=undercurl ctermul=141
hi Statement guifg=#b483ff guibg=NONE guisp=NONE gui=NONE ctermfg=141 ctermbg=NONE cterm=NONE term=NONE
hi StatusLine guifg=#eeebff guibg=#241e2e guisp=NONE gui=NONE ctermfg=189 ctermbg=234 cterm=NONE term=NONE
hi StatusLineNC guifg=#706897 guibg=#241e2e guisp=NONE gui=NONE ctermfg=60 ctermbg=234 cterm=NONE term=NONE
hi String guifg=#b9ff91 guibg=NONE guisp=NONE gui=NONE ctermfg=156 ctermbg=NONE cterm=NONE term=NONE
hi Substitute guifg=#241e2e guibg=#fb97ff guisp=NONE gui=bold ctermfg=234 ctermbg=213 cterm=bold term=bold
hi TabLine guifg=#706897 guibg=#241e2e guisp=NONE gui=NONE ctermfg=60 ctermbg=234 cterm=NONE term=NONE
hi TabLineFill guifg=#706897 guibg=#241e2e guisp=NONE gui=NONE ctermfg=60 ctermbg=234 cterm=NONE term=NONE
hi TabLineSel guifg=#eeebff guibg=#342d42 guisp=NONE gui=bold ctermfg=189 ctermbg=236 cterm=bold term=bold
hi TermCursor guifg=#241e2e guibg=#eeebff guisp=NONE gui=NONE ctermfg=234 ctermbg=189 cterm=NONE term=NONE
hi Terminal guifg=#eeebff guibg=#110f15 guisp=NONE gui=NONE ctermfg=189 ctermbg=233 cterm=NONE term=NONE
hi Title guifg=#ffa770 guibg=NONE guisp=NONE gui=NONE ctermfg=216 ctermbg=NONE cterm=NONE term=NONE
hi Todo guifg=#ffa770 guibg=NONE guisp=NONE gui=NONE ctermfg=216 ctermbg=NONE cterm=NONE term=NONE
hi Type guifg=#6daeff guibg=NONE guisp=NONE gui=NONE ctermfg=75 ctermbg=NONE cterm=NONE term=NONE
hi Variable guifg=fg guibg=NONE guisp=NONE gui=NONE ctermfg=fg ctermbg=NONE cterm=NONE term=NONE
hi VertSplit guifg=#342d42 guibg=#110f15 guisp=NONE gui=NONE ctermfg=236 ctermbg=233 cterm=NONE term=NONE
hi Visual guifg=NONE guibg=#342d42 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE term=NONE
hi WarningMsg guifg=#ffd986 guibg=NONE guisp=NONE gui=bold ctermfg=222 ctermbg=NONE cterm=bold term=bold
hi Whitespace guifg=#342d42 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE term=NONE
hi WildMenu guifg=#241e2e guibg=#76ddff guisp=NONE gui=bold ctermfg=234 ctermbg=81 cterm=bold term=bold
hi WinBar guifg=#eeebff guibg=#241e2e guisp=NONE gui=NONE ctermfg=189 ctermbg=234 cterm=NONE term=NONE
hi WinBarNC guifg=#706897 guibg=#241e2e guisp=NONE gui=NONE ctermfg=60 ctermbg=234 cterm=NONE term=NONE

if has('gui_running') || s:tgc
  if s:transp_bg == 1
    hi Normal guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guibg=NONE gui=NONE cterm=NONE
    hi EndOfBuffer guibg=NONE gui=NONE cterm=NONE
    hi FloatBorder guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guibg=NONE gui=NONE cterm=NONE
    hi LineNr guibg=NONE gui=NONE cterm=NONE
    hi MsgArea guibg=NONE gui=NONE cterm=NONE
    hi NormalFloat guibg=NONE gui=NONE cterm=NONE
    hi NormalNC guibg=NONE gui=NONE cterm=NONE
    hi SignColumn guibg=NONE gui=NONE cterm=NONE
    hi StatusLine guibg=NONE gui=NONE cterm=NONE
    hi StatusLineNC guibg=NONE gui=NONE cterm=NONE
    hi TabLine guibg=NONE gui=NONE cterm=NONE
    hi TabLineFill guibg=NONE gui=NONE cterm=NONE
    hi TabLineSel guibg=NONE gui=NONE cterm=NONE
    hi Terminal guibg=NONE gui=NONE cterm=NONE
    hi VertSplit guibg=NONE gui=NONE cterm=NONE
    hi WinBar guibg=NONE gui=NONE cterm=NONE
    hi WinBarNC guibg=NONE gui=NONE cterm=NONE
  endif
endif

if s:tgc || s:t_Co >= 256
  if s:transp_bg == 1
    hi Normal ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermbg=NONE cterm=NONE
    hi FloatBorder ctermbg=NONE cterm=NONE
    hi FoldColumn ctermbg=NONE cterm=NONE
    hi LineNr ctermbg=NONE cterm=NONE
    hi MsgArea ctermbg=NONE cterm=NONE
    hi NormalFloat ctermbg=NONE cterm=NONE
    hi NormalNC ctermbg=NONE cterm=NONE
    hi SignColumn ctermbg=NONE cterm=NONE
    hi StatusLine ctermbg=NONE cterm=NONE
    hi StatusLineNC ctermbg=NONE cterm=NONE
    hi TabLine ctermbg=NONE cterm=NONE
    hi TabLineFill ctermbg=NONE cterm=NONE
    hi TabLineSel ctermbg=NONE cterm=NONE
    hi Terminal ctermbg=NONE cterm=NONE
    hi VertSplit ctermbg=NONE cterm=NONE
    hi WinBar ctermbg=NONE cterm=NONE
    hi WinBarNC ctermbg=NONE cterm=NONE
  endif
  finish
endif

if s:t_Co >= 16
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Comment ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CurSearch ctermfg=NONE ctermbg=NONE cterm=bold
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=bold
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi FloatBorder ctermfg=NONE ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Function ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=fg ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold
  hi LineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MsgArea ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Operator ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=NONE ctermbg=NONE cterm=bold
  hi Search ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Special ctermfg=fg ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Statement ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi String ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Substitute ctermfg=NONE ctermbg=NONE cterm=bold
  hi TabLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi TermCursor ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Terminal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Title ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Todo ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Variable ctermfg=fg ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi Whitespace ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi WinBar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WinBarNC ctermfg=NONE ctermbg=NONE cterm=NONE
  finish
endif

if s:t_Co >= 8
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Comment ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CurSearch ctermfg=NONE ctermbg=NONE cterm=bold
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=bold
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi FloatBorder ctermfg=NONE ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Function ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=fg ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold
  hi LineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MsgArea ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Operator ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=NONE ctermbg=NONE cterm=bold
  hi Search ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Special ctermfg=fg ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Statement ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi String ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Substitute ctermfg=NONE ctermbg=NONE cterm=bold
  hi TabLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi TermCursor ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Terminal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Title ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Todo ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Variable ctermfg=fg ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi Whitespace ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi WinBar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WinBarNC ctermfg=NONE ctermbg=NONE cterm=NONE
  if s:transp_bg == 1
    hi Normal ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermbg=NONE cterm=NONE
    hi FloatBorder ctermbg=NONE cterm=NONE
    hi FoldColumn ctermbg=NONE cterm=NONE
    hi LineNr ctermbg=NONE cterm=NONE
    hi MsgArea ctermbg=NONE cterm=NONE
    hi NormalFloat ctermbg=NONE cterm=NONE
    hi NormalNC ctermbg=NONE cterm=NONE
    hi SignColumn ctermbg=NONE cterm=NONE
    hi StatusLine ctermbg=NONE cterm=NONE
    hi StatusLineNC ctermbg=NONE cterm=NONE
    hi TabLine ctermbg=NONE cterm=NONE
    hi TabLineFill ctermbg=NONE cterm=NONE
    hi TabLineSel ctermbg=NONE cterm=NONE
    hi Terminal ctermbg=NONE cterm=NONE
    hi VertSplit ctermbg=NONE cterm=NONE
    hi WinBar ctermbg=NONE cterm=NONE
    hi WinBarNC ctermbg=NONE cterm=NONE
  endif
  finish
endif

" vim: et ts=8 sw=2 sts=2
